import os

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "AIzaSyAOorokSXnBGeDFte5_LoxXWh6MYPIOq7I")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "7605033751:AAFAkK096F2N65qS5pMDGEQfP8FzN5rxtIY")
CHANNEL_ID = os.getenv("CHANNEL_ID", "UCY5QxBSs6MVM1OOOAG9I2LQ")
COMMENT_TEXT = os.getenv("COMMENT_TEXT", "Nice Video! 🚀")
